#!/usr/bin/env bash
#script displays Nest School 1-10, except bad luck on 4, good luck on 8
i=0
while ((i < 10))
do
	((i++))
	if 
		[ $i = 4 ]
	then 
		echo "bad luck"
	elif 
		[ $i = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
