#!/usr/bin/env bash
#displays info about school file
i=school
if [ -e $i ]; then
	echo "school file exists"
else
	echo "school file does not exist"
	exit 1
fi
if [ ! -s $i ]; then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
if [ -f $i ]; then
	echo "school is a regular file"
fi
