#!/bin/bash

if [ $# -eq 0 ]; then
	  echo "Usage: $0 <script_name>"
	    exit 1
fi

script_name="$1"

# Check if the file already exists
if [ -e "$script_name" ]; then
	  echo "File '$script_name' already exists."
	    exit 1
fi

# Create the file with the shebang line
echo -e "#!/bin/bash\n" > "$script_name"

# Add execute permission
chmod +x "$script_name"

# Open the file in Vim
vim "$script_name"
